---
apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
  namespace: devops
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /mnt/jenkins-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volume-claim
  namespace: devops
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: jenkins-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: docker-exec
          mountPath: /usr/bin/docker
        - name: kubectl-exec
          mountPath: /usr/bin/kubectl
        - name: jenkins-data
          mountPath: /var/jenkins_home
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: docker-exec
        hostPath:
          path: /usr/bin/docker
      - name: kubectl-exec
        hostPath:
          path: /usr/bin/kubectl
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
  type: NodePort
